name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: test
        run: pnpm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - run: |
          docker build -f docker/prod/Dockerfile \
          -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app \
          --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --build-arg NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
          --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
          --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
          --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          .

      - run: docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app

      - name: Deploy
        run: |
          gcloud run deploy next-app \
            --project=${{ secrets.PROJECT_ID }} \
            --image=asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app:latest \
            --region=asia-northeast1 \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \
            --port=3000 \
            --allow-unauthenticated
