name: "Deploy"

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -f docker/prod/Dockerfile \
          -t asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app \
          --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --build-arg NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
          --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
          --build-arg GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
          --build-arg GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          .

      - name: Push Docker image
        run: docker push asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy next-app \
            --project=${{ secrets.PROJECT_ID }} \
            --image=asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/fullstack-next-images/next-app:latest \
            --region=asia-northeast1 \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \
            --port=3000 \
            --allow-unauthenticated
